// @ts-nocheck
'use client'
import{useState}from'react'
import{useRouter}from'next/navigation'
import{createBrowserClient}from'@/lib/supabase'
import{VOZIT_LOGO}from'@/lib/logo'
const TYPES=[{id:'eyewitness',l:'Eyewitness',d:'On the ground, reporting what you see'},{id:'journalist',l:'Journalist',d:'Professional reporting background'},{id:'activist',l:'Advocate',d:'Amplifying voices and causes'},{id:'hobbyist',l:'Observer',d:'Curious citizen documenting life'}]
const TOPICS=['conflict','climate','protest','politics','health','infrastructure','culture','wildlife']
const PROVIDERS=[
  {id:'stripe',icon:'🏦',l:'Bank Transfer (Stripe)',d:'46+ countries. Direct to bank or debit card.',r:'US, EU, UK, CA, AU +'},
  {id:'paypal',icon:'🅿️',l:'PayPal',d:'200+ countries. Payout to PayPal balance.',r:'Global'},
  {id:'wise',icon:'💸',l:'Wise (TransferWise)',d:'Low-fee bank transfers at real exchange rate.',r:'80+ countries'},
  {id:'payoneer',icon:'🌐',l:'Payoneer',d:'Bank transfer or Payoneer prepaid card.',r:'200+ countries'},
  {id:'flutterwave',icon:'📱',l:'Mobile Money (M-Pesa)',d:'M-Pesa, MTN, Airtel Money. $5 minimum.',r:'Nigeria, Kenya, Ghana, SA +'},
  {id:'chipper',icon:'🐦',l:'Chipper Cash',d:'Chipper wallet or mobile money. Zero fees.',r:'7 African countries'},
  {id:'worldremit',icon:'🌍',l:'WorldRemit',d:'Bank, mobile money, or cash pickup.',r:'130+ countries'},
  {id:'crypto',icon:'₿',l:'Crypto (USDC/USDT)',d:'To any wallet address. No bank needed.',r:'Anywhere with internet'},
]
type Step='profile'|'topics'|'revenue'|'complete'
export default function P(){const router=useRouter();const sb=createBrowserClient();const[step,setStep]=useState<Step>('profile');const[loading,setLoading]=useState(false);const[type,setType]=useState('');const[topics,setTopics]=useState<string[]>([]);const[optIn,setOptIn]=useState(false);const[provider,setProvider]=useState('')
async function saveProfile(){setLoading(true);try{const{data:{user}}=await sb.auth.getUser();if(!user)return;await sb.from('users').update({reporter_type:type}).eq('id',user.id);setStep('topics')}finally{setLoading(false)}}
async function saveTopics(){setLoading(true);try{const{data:{user}}=await sb.auth.getUser();if(!user)return;await sb.from('users').update({topics}).eq('id',user.id);setStep('revenue')}finally{setLoading(false)}}
async function saveRevenue(){setLoading(true);try{const{data:{user}}=await sb.auth.getUser();if(!user)return;if(optIn&&provider){await sb.from('users').update({revenue_enabled:true,payout_provider:provider}).eq('id',user.id);if(provider==='stripe'){const r=await fetch('/api/payouts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:'stripe'})});const d=await r.json();if(d.onboarding_url){window.location.href=d.onboarding_url;return}}}setStep('complete')}finally{setLoading(false)}}
const cs={p:{minHeight:'100vh',background:'#f5f5f5',display:'flex'as const,alignItems:'center'as const,justifyContent:'center'as const,padding:24},c:{maxWidth:440,width:'100%'},o:{padding:12,borderRadius:10,border:'1px solid #eee',background:'#fff',cursor:'pointer',marginBottom:8,color:'#333',fontSize:13,transition:'border-color 0.15s'}}
if(step==='profile')return(<div style={cs.p}><div className='card' style={{...cs.c,padding:28}}><div style={{textAlign:'center',marginBottom:20}}><img src={VOZIT_LOGO} alt='VozIt' style={{height:48,width:48,borderRadius:10,margin:'0 auto 8px'}}/></div><h2 style={{color:'#1a1a1a',fontSize:18,marginBottom:4}}>What kind of reporter?</h2><p style={{color:'#888',fontSize:12,marginBottom:16}}>This helps us match you with assignments</p>{TYPES.map(t=>(<div key={t.id} onClick={()=>setType(t.id)} style={{...cs.o,borderColor:type===t.id?'#FE3D07':'#eee',background:type===t.id?'#FEF3E6':'#fff'}}><div style={{fontWeight:600}}>{t.l}</div><div style={{fontSize:11,color:'#888',marginTop:2}}>{t.d}</div></div>))}<button onClick={saveProfile} disabled={!type||loading} className='btn-primary' style={{width:'100%',opacity:type?1:0.5,marginTop:8}}>{loading?'...':'Continue'}</button></div></div>)
if(step==='topics')return(<div style={cs.p}><div className='card' style={{...cs.c,padding:28}}><h2 style={{color:'#1a1a1a',fontSize:18,marginBottom:4}}>Topics you cover</h2><p style={{color:'#888',fontSize:12,marginBottom:16}}>Select all that apply</p><div style={{display:'flex',flexWrap:'wrap',gap:8,marginBottom:16}}>{TOPICS.map(t=>(<span key={t} onClick={()=>setTopics(ts=>ts.includes(t)?ts.filter(x=>x!==t):[...ts,t])} style={{...cs.o,display:'inline-block',width:'auto',borderColor:topics.includes(t)?'#FE3D07':'#eee',background:topics.includes(t)?'#FEF3E6':'#fff',marginBottom:0,padding:'8px 14px',borderRadius:20}}>{t}</span>))}</div><button onClick={saveTopics} disabled={loading} className='btn-primary' style={{width:'100%'}}>{loading?'...':'Continue'}</button></div></div>)
if(step==='revenue')return(<div style={cs.p}><div className='card' style={{...cs.c,padding:28}}><h2 style={{color:'#1a1a1a',fontSize:18,marginBottom:4}}>Earn for your reporting</h2><p style={{color:'#888',fontSize:13,marginBottom:16}}>VozIt shares revenue — you keep up to 70%.</p>
<div onClick={()=>setOptIn(!optIn)} style={{...cs.o,borderColor:optIn?'#22C55E':'#eee',display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontWeight:600}}>{optIn?'Revenue enabled ✓':'Join revenue program'}</span><div style={{width:44,height:24,borderRadius:12,background:optIn?'#22C55E':'#ddd',position:'relative',transition:'background 0.2s'}}><div style={{width:18,height:18,borderRadius:9,background:'white',position:'absolute',top:3,left:optIn?23:3,transition:'left 0.2s'}}/></div></div>
{optIn&&<><div style={{padding:14,background:'#fafafa',borderRadius:10,border:'1px solid #f0f0f0',marginTop:12,marginBottom:16}}>
<div style={{fontSize:12,fontWeight:600,color:'#1a1a1a',marginBottom:10}}>Revenue Tiers</div>
{[{l:'Starter',c:'#22C55E',r:'50%',req:'0–25 reports'},{l:'Silver',c:'#94A3B8',r:'55%',req:'26–100, 80%+ credibility'},{l:'Gold',c:'#EAB308',r:'65%',req:'101–499, 90%+ credibility'},{l:'Platinum',c:'#8B5CF6',r:'70%',req:'500+, 95%+ credibility'}].map(t=>(<div key={t.l} style={{display:'flex',alignItems:'center',gap:8,marginBottom:6}}><div style={{width:8,height:8,borderRadius:4,background:t.c,flexShrink:0}}/><span style={{flex:1,fontSize:12,fontWeight:600}}>{t.l}</span><span style={{fontSize:10,color:'#888'}}>{t.req}</span><span style={{fontSize:12,fontWeight:700,color:t.c,minWidth:32,textAlign:'right'}}>{t.r}</span></div>))}
<div style={{fontSize:10,color:'#999',textAlign:'center',marginTop:8,paddingTop:8,borderTop:'1px solid #eee'}}>No fees — VozIt absorbs all payout costs</div>
</div>
<div style={{fontSize:12,fontWeight:600,color:'#1a1a1a',marginBottom:10}}>Choose payout method</div>
{PROVIDERS.map(p=>(<div key={p.id} onClick={()=>setProvider(p.id)} style={{...cs.o,borderColor:provider===p.id?'#0a8fe8':'#eee',background:provider===p.id?'#EFF8FF':'#fff',display:'flex',gap:10,alignItems:'flex-start'}}><span style={{fontSize:20,lineHeight:'1'}}>{p.icon}</span><div style={{flex:1}}><div style={{fontWeight:600,fontSize:13}}>{p.l}</div><div style={{fontSize:11,color:'#888',marginTop:1}}>{p.d}</div><div style={{fontSize:10,color:'#0a8fe8',marginTop:2}}>{p.r}</div></div>{provider===p.id&&<span style={{color:'#0a8fe8',fontWeight:700}}>✓</span>}</div>))}
</>}
<button onClick={optIn?saveRevenue:()=>setStep('complete')} disabled={optIn&&!provider} className='btn-primary' style={{width:'100%',marginTop:12,opacity:(optIn&&!provider)?0.5:1}}>{optIn?(provider?'Continue':'Select a method'):'Skip for now'}</button>
</div></div>)
return(<div style={cs.p}><div className='card' style={{...cs.c,padding:28,textAlign:'center'}}><div style={{fontSize:48,marginBottom:12}}>{'\u2705'}</div><h2 style={{color:'#1a1a1a',fontSize:18,marginBottom:8}}>You{"'"}re ready!</h2><p style={{color:'#888',fontSize:13,marginBottom:16}}>Start reporting what you witness.</p><button onClick={()=>router.push('/feed')} className='btn-primary' style={{width:'100%'}}>Go to feed</button></div></div>)}
