// @ts-nocheck
'use client'
import{useState}from'react'
import{useRouter}from'next/navigation'
import{ShareButton}from'@/components/share/ShareButton'
const TC:Record<string,{c:string,bg:string,l:string}>={starter:{c:'#22C55E',bg:'#ECFDF5',l:'Starter'},silver:{c:'#94A3B8',bg:'#F0F4F8',l:'Silver'},gold:{c:'#EAB308',bg:'#FFF8E6',l:'Gold'},platinum:{c:'#8B5CF6',bg:'#F5F0FF',l:'Platinum'}}
export function ReportDetailClient({report:r,seriesReports}:{report:any,seriesReports:any[]}){const router=useRouter();const[voted,setVoted]=useState<'up'|'down'|null>(null);const[votes,setVotes]=useState({up:r.upvotes,down:r.downvotes});const t=TC[r.user?.tier||'starter']||TC.starter
async function vote(d:'up'|'down'){if(voted===d)return;setVoted(d);setVotes(v=>({up:v.up+(d==='up'?1:0),down:v.down+(d==='down'?1:0)}));fetch('/api/votes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({report_id:r.id,value:d==='up'?1:-1})}).catch(()=>{})}
return(<div style={{background:'#fff',minHeight:'100vh'}}><div style={{background:'linear-gradient(to right,#f0e8d8,#b8d8f0 25%,#50b0e8 50%,#18a0e8 75%,#0a3ff1)',padding:'10px 16px',display:'flex',alignItems:'center',gap:12}}><span onClick={()=>router.back()} style={{cursor:'pointer',color:'#fff',fontSize:18}}>{'\u2039'}</span><span style={{fontSize:14,fontWeight:600,color:'#fff',flex:1,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{r.title}</span></div>
<div style={{height:200,background:'#0a1e30',display:'flex',alignItems:'center',justifyContent:'center'}}>{r.playback_id?<div>Video</div>:<span style={{color:'rgba(255,255,255,0.2)'}}>Video processing...</span>}</div>
<div style={{maxWidth:600,margin:'0 auto',padding:'14px 16px 60px'}}><h1 style={{fontSize:18,fontWeight:700,color:'#1a1a1a',lineHeight:1.4,marginBottom:4}}>{r.title}</h1><div style={{fontSize:12,color:'#00AACC',fontWeight:500,marginBottom:12}}>{r.location_name} · {new Date(r.created_at).toLocaleDateString()}</div>
{r.description&&<p style={{fontSize:14,color:'#333',lineHeight:1.6,marginBottom:16}}>{r.description}</p>}
<div style={{background:'#fafafa',borderRadius:10,padding:14,marginBottom:16,border:'1px solid #f0f0f0'}}>{[{l:'WHO',v:r.who,c:'#B53D0F'},{l:'WHAT',v:r.what,c:'#1565C0'},{l:'WHERE',v:r.where_text||r.location_name,c:'#085041'},{l:'WHEN',v:r.when_happened?new Date(r.when_happened).toLocaleString():'',c:'#854F0B'},{l:'WHY',v:r.why,c:'#993556'}].map(w=>w.v?(<div key={w.l} style={{display:'flex',gap:10,marginBottom:8}}><span style={{fontSize:10,fontWeight:700,color:w.c,width:40,flexShrink:0}}>{w.l}</span><span style={{fontSize:13,color:'#333',lineHeight:1.4}}>{w.v}</span></div>):null)}</div>
<div style={{display:'flex',alignItems:'center',gap:10,padding:'14px 0',borderTop:'1px solid #f0f0f0',borderBottom:'1px solid #f0f0f0',marginBottom:14}}>
<div style={{width:36,height:36,borderRadius:18,background:t.c,display:'flex',alignItems:'center',justifyContent:'center',fontSize:12,fontWeight:700,color:'#fff'}}>{(r.user?.display_name||'?').slice(0,2).toUpperCase()}</div>
<div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,color:'#1a1a1a'}}>@{r.user?.username} <span style={{fontSize:9,fontWeight:600,padding:'1px 5px',borderRadius:3,background:t.bg,color:t.c,marginLeft:4}}>{'\u2605'} {t.l}</span></div><div style={{fontSize:11,color:'#888'}}>{Math.round(r.credibility_pct||80)}% credibility</div></div>
<button onClick={()=>vote('up')} style={{padding:'8px 14px',borderRadius:8,border:'1px solid #eee',cursor:'pointer',fontSize:13,fontWeight:600,background:voted==='up'?'#ECFDF5':'#fff',color:voted==='up'?'#085041':'#333',fontFamily:'inherit'}}>{'\u25b2'} {votes.up}</button>
<button onClick={()=>vote('down')} style={{padding:'8px 14px',borderRadius:8,border:'1px solid #eee',cursor:'pointer',fontSize:13,fontWeight:600,background:voted==='down'?'#FEF2F2':'#fff',color:voted==='down'?'#DC2626':'#333',fontFamily:'inherit'}}>{'\u25bc'} {votes.down}</button>
</div>
<div style={{display:'flex',gap:8,marginBottom:14}}><div style={{flex:1,padding:10,borderRadius:8,border:'1px solid #eee',textAlign:'center',cursor:'pointer',fontSize:11,fontWeight:600,color:'#555'}}>X</div><div style={{flex:1,padding:10,borderRadius:8,border:'1px solid #eee',textAlign:'center',cursor:'pointer',fontSize:11,fontWeight:600,color:'#555'}}>Facebook</div><div style={{flex:1,padding:10,borderRadius:8,border:'1px solid #eee',textAlign:'center',cursor:'pointer',fontSize:11,fontWeight:600,color:'#555'}}>Copy link</div></div>
</div></div>)}
