// @ts-nocheck
'use client'
import{useState,useEffect,useCallback}from'react'
import{useRouter}from'next/navigation'
type Tab='queue'|'stats'|'history'
export default function P(){const router=useRouter();const[tab,setTab]=useState<Tab>('queue');const[reports,setReports]=useState<any[]>([]);const[stats,setStats]=useState<any>(null);const[actions,setActions]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[total,setTotal]=useState(0);const[selected,setSelected]=useState<string|null>(null);const[result,setResult]=useState<string|null>(null)
const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/admin/moderation?view='+tab);if(!r.ok){router.push('/feed');return};const d=await r.json();if(tab==='queue'){setReports(d.reports||[]);setTotal(d.total||0)}else if(tab==='stats'){setStats(d.stats);setActions(d.recentActions||[])}else{setActions(d.actions||[]);setTotal(d.total||0)}}catch{router.push('/feed')}finally{setLoading(false)}},[tab,router])
useEffect(()=>{load()},[load])
async function act(id:string,action:string,reason?:string){const r=await fetch('/api/admin/moderation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({report_id:id,action,reason})});const d=await r.json();if(d.ok){setResult(d.action);setReports(rs=>rs.filter(x=>x.id!==id));setTotal(t=>t-1)}}
return(<div style={{minHeight:'100vh',background:'#fff'}}><div style={{background:'linear-gradient(to right,#f0e8d8,#0a3ff1)',padding:'12px 20px',display:'flex',alignItems:'center',gap:10}}><span style={{fontSize:15,fontWeight:700,color:'white'}}>Moderation</span></div>
<div style={{maxWidth:900,margin:'0 auto',padding:'16px 20px'}}><div style={{display:'flex',background:'#f5f5f5',borderRadius:10,padding:3,marginBottom:16}}>{(['queue','stats','history']as Tab[]).map(t=>(<button key={t} onClick={()=>{setTab(t);setSelected(null)}} style={{flex:1,padding:'10px 0',borderRadius:8,border:'none',cursor:'pointer',fontSize:13,fontWeight:tab===t?600:400,background:tab===t?'#fff':'transparent',color:tab===t?'#1a1a1a':'#999',fontFamily:'inherit',boxShadow:tab===t?'0 1px 3px rgba(0,0,0,0.1)':'none'}}>{t}{t==='queue'&&total>0?` (${total})`:''}</button>))}</div>
{result&&<div style={{background:'#ECFDF5',borderRadius:10,padding:'10px 14px',marginBottom:12,fontSize:13,color:'#085041'}}>{result}</div>}
{loading&&<div style={{textAlign:'center',padding:40,color:'#999'}}>Loading...</div>}
{!loading&&tab==='queue'&&reports.map(r=>(<div key={r.id} onClick={()=>setSelected(selected===r.id?null:r.id)} className='card' style={{marginBottom:8,padding:14,cursor:'pointer',borderColor:selected===r.id?'#FE3D07':'#f0f0f0'}}><div style={{fontSize:14,fontWeight:600,color:'#1a1a1a',marginBottom:4}}>{r.title}</div><div style={{fontSize:12,color:'#888'}}>@{r.user?.username} · {r.credibility_pct}% · {'\u25b2'}{r.upvotes} {'\u25bc'}{r.downvotes}</div>{selected===r.id&&<div style={{marginTop:10,display:'flex',flexWrap:'wrap',gap:6}}><button onClick={e=>{e.stopPropagation();act(r.id,'restore')}} style={{padding:'8px 14px',borderRadius:8,border:'none',cursor:'pointer',fontSize:12,background:'#ECFDF5',color:'#085041',fontFamily:'inherit'}}>Restore</button><button onClick={e=>{e.stopPropagation();act(r.id,'keep_flagged')}} style={{padding:'8px 14px',borderRadius:8,border:'none',cursor:'pointer',fontSize:12,background:'#FFF8E6',color:'#B8860B',fontFamily:'inherit'}}>Keep flagged</button><button onClick={e=>{e.stopPropagation();const reason=prompt('Reason:');if(reason!==null)act(r.id,'remove',reason)}} style={{padding:'8px 14px',borderRadius:8,border:'none',cursor:'pointer',fontSize:12,background:'#FEF2F2',color:'#DC2626',fontFamily:'inherit'}}>Remove+strike</button><button onClick={e=>{e.stopPropagation();if(confirm('PERMANENT BAN?'))act(r.id,'remove_ban','AI content')}} style={{padding:'8px 14px',borderRadius:8,border:'none',cursor:'pointer',fontSize:12,background:'#FEF2F2',color:'#DC2626',fontFamily:'inherit'}}>Ban</button></div>}</div>))}
{!loading&&tab==='stats'&&stats&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))',gap:10}}>{[{n:stats.totalReports,l:'Total'},{n:stats.flaggedInQueue,l:'Queue'},{n:stats.totalRemoved,l:'Removed'},{n:stats.bannedUsers,l:'Banned'}].map(({n,l})=>(<div key={l} className='card' style={{padding:16,textAlign:'center'}}><div style={{fontSize:28,fontWeight:700,color:'#1a1a1a'}}>{n||0}</div><div style={{fontSize:12,color:'#888',marginTop:4}}>{l}</div></div>))}</div>}
{!loading&&tab==='history'&&actions.map((a:any)=>(<div key={a.id} className='card' style={{padding:'10px 14px',marginBottom:6,fontSize:12,color:'#888'}}><span style={{color:'#1a1a1a',fontWeight:600}}>@{a.moderator?.username}</span> {a.result||a.action}</div>))}
</div></div>)}
